### ISSUE TITLE
file_get_contents doesn't read full file

### ISSUE THREAD

**Issue by kelunik** [RobberPhex/pkgist#3]
https://github.com/RobberPhex/pkgist/blob/0ccc7ebe9f4b5e2385ce7a2dde562e6ed1e52ba2/app/App.php#L245-L253

^ That snippet doesn't read the full file if it's larger. `InputStream::read()` only reads a single chunk, that might not be enough for a larger file. You can use `yield new Amp\ByteStream\Message($handle)` instead, which buffers the complete stream.

**Comment by robberphex** [comment]
Hi, thank you.

fixed in dc1380d5a14143d5529890adbd076c6bcbfd8fb7
